## Numpy Array Operations 


In [24]:
import numpy as np

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Basic Slicing: ",arr[2:7])
print("Slicing With Step: ",arr[1:8:2])
print("Negative indexing: ",arr[-3])
print("Negative indexing: ",arr[-8:-7])

Basic Slicing:  [3 4 5 6 7]
Slicing With Step:  [2 4 6 8]
Negative indexing:  7
Negative indexing:  [2]


In [26]:
arr_2D = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element: ",arr_2D[1,2])
print("Entire row: ",arr_2D[1])
print("Entire column: ",arr_2D[:,1])
#print("2D array slicing: ",arr_2D[1,1])

Specific element:  6
Entire row:  [4 5 6]
Entire column:  [2 5 8]


### Sorting


In [27]:
unsorted = np.array([3, 1, 2, 4, 5,9, 8, 7, 6])
print("Unsorted array: ",unsorted)
sorted = np.sort(unsorted)
print("Sorted array: ",sorted)

# arr_2D_unsorted = np.array([[3,2,1],
#                             [6,5,4],
#                             [9,8,7]])

arr_2D_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array by column:\n",np.sort(arr_2D_unsorted, axis=0))
print("Sorted 2D array by row:\n",np.sort(arr_2D_unsorted, axis=1))

Unsorted array:  [3 1 2 4 5 9 8 7 6]
Sorted array:  [1 2 3 4 5 6 7 8 9]
Sorted 2D array by column:
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row:
 [[1 3]
 [1 2]
 [2 3]]


### Filter


In [28]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0] 
# numbers % 2 == 0 is is a mask 
print("Even numbers: ",even_numbers)

Even numbers:  [ 2  4  6  8 10]


### Filter with mask


In [29]:
mask = numbers > 5 # Mask stores expression for evaluation 
print("Numbers greater than 5: " , numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


### Fancy Indexing vs np. where()

In [32]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [39]:
condition_Arry = np.where(numbers >= 5, "true", numbers)
print(condition_Arry) 

['1' '2' '3' '4' 'true' 'true' 'true' 'true' 'true' 'true']


### Adding and removing Data

In [40]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined  = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


### Array compatibiltiy


In [45]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatiblity Shapes: ", a.shape == b.shape)

Compatiblity Shapes:  True


In [49]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))

print(original)
print("\n")
print(with_new_row)

new_col = np.array([[111], [222]])
with_new_col = np.hstack((original, new_col))
print("\n")
print(with_new_col)

[[1 2]
 [3 4]]


[[1 2]
 [3 4]
 [5 6]]


[[  1   2 111]
 [  3   4 222]]


In [51]:
arr =  np.array([1,2,3,4,5,6,7,8,9])
deleted = np.delete(arr, 3)
print("Array afer dletion: ",deleted)

Array afer dletion:  [1 2 3 5 6 7 8 9]
