## Numpy array and basics


In [2]:
import numpy as np

### Creating Array from List

In [3]:
arr_1D = np.array([1,2,3,4,5])
arr_2D = np.array([[1,2,3],[4,5,6]])
print("1D array: ", arr_1D)
print("2D array: ", arr_2D)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array


In [4]:
py_list = [1,2,3]
print("Python list multiplication", py_list*2)

np_array = np.array ([1,2,3])
print("Python array multiplication", np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print(" \n List Operation time: ", time.time()-start)

start = time.time()
np_array = np.arange(1000000)*2 
print(" \n Numpy Operation time: ", time.time()-start)

Python list multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 6]
 
 List Operation time:  0.09272170066833496
 
 Numpy Operation time:  0.007998466491699219


### creating array from scratch 


In [5]:
Zeros  = np.zeros((3,5))
print("Zeros array: \n", Zeros)

Ones = np.ones((3,5))
print("Ones array: \n", Ones)

full = np.full((2,2), 7)
print("Full array: \n", full)

random = np.random.random((2,3))
print("Random array: \n", random)

sequence = np.arange(0, 11, 2)
print("Sequence array: \n", sequence)


Zeros array: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Full array: 
 [[7 7]
 [7 7]]
Random array: 
 [[0.14372046 0.72045786 0.46931281]
 [0.8567315  0.64792022 0.92778228]]
Sequence array: 
 [ 0  2  4  6  8 10]


### Vector Matrix and Tensor 

In [6]:
Vector =  np.array([1,2,3,4,5])
print("Vector: ", Vector)

Matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix: \n", Matrix)

Tensor = np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]]])
print("Tensor: \n", Tensor)

Vector:  [1 2 3 4 5]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Array Propeties 


In [13]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12.83]])

print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Dimensions of array: ", arr.ndim)
print("Data type of array: ", arr.dtype)

Shape of array:  (3, 4)
Size of array:  12
Dimensions of array:  2
Data type of array:  float64


### Array Reshaping

In [27]:
arr = np.arange(12)
print("Original array: ", arr)
print("Shape of array: ", arr.shape)

reshaped = arr.reshape(2, 6)
print("\n Reshaped array: \n", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array: ", flattened)


# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
# raveled1 = arr.ravel()
# print("\n Raveled array original: ", arr)    
print("\n Raveled array: ", raveled)    


# Transpose
transpose = reshaped.T
print("\n Transpose array: \n", transpose)



Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape of array:  (12,)

 Reshaped array: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

 Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array: 
 [[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
